### ISSUE TITLE
error No key 'geometry': Not an HTML form submission (Content-Type: )

### ISSUE THREAD

**Issue by JorgeSanzS** [OSM-es/CatAtom2Osm#38]
Error nuevo también que antes no sucedía. En el gestor de tareas le doy a crear un nuevo proyecto. Después importo archivo zoning.geojson y me sale el mapa bien importado. Selecciono geometrías arbitrarias y cuando le doy a Crear proyecto me salta el siguiente error:
No key 'geometry': Not an HTML form submission (Content-Type: )

He probado con otras importaciones ya realizadas que no dieron problemas. Y al intentar subir el archivo me sale el mismo error. Así que no debería ser problema del archivo que subo. No sé si habra cambiado algo en el gestor de tareas que pueda provocar el error.

**Comment by javiersanp** [comment]
Hola.

+
-
5000 km
3000 mi
Leaflet | Datos del mapa: © OpenStreetMap contributors
Paso 1

la área de interés en el mapa.

o

un archivo GeoJSON, KML, o SHP compreso. ¿Quiere utilizar alternativamente un archivo .osm?
Puede utilizar GeoJSON.io para convertirlo a GeoJSON.

Descarga el código en github.

Sobre el Gestor de Tareas
Find administrator at mapeadocolaborativo@gmail.com
Follow Mapeado Colaborativo on TwitterNo
Parece un problema del gestor de tareas. Si intento crea un proyecto dibujando el área de interés en lugar de importar un json termino con un error 'No se pudo crear el proyecto tile_size'.

No se si habrá modificado la versión del gestor. A ver si @alejandroscf puede decirnos algo.

**Comment by alejandroscf** [comment]
Arreglado

**Comment by javiersanp** [comment]
Gracias.
