### ISSUE TITLE
¿Error in 'zoning.geojson' file? Geometry type does not match column type (Multipolygon)

### ISSUE THREAD

**Issue by JordiMFimport** [OSM-es/CatAtom2Osm#40]
Me ha surgido un último problema a la hora de crear el proyecto en el Gestor
de Tareas. En el Paso 3 del gestor, después de adjuntar el archivo
"zoning.geojson", me devuelve al Paso 1 con el siguiente mensaje informando
del error:

"Lo sentimos, no se pudo crear el proyecto. (DataError) Geometry type
(GeometryCollection) does not match column type (Multipolygon)"

Me he fijado que en la previsualización del mapa, en el paso 3, se observa
una área no sombreada de azul por el gestor [1]. Es decir, parece que el
Gestor de Tareas no detecta esa tarea. Esta misma área sí que queda
sombreada en la previsualización si utilizo el archivo
"rustic_zoning.geojson".

He usado la versión de desarrollo 1.2 de CatAtom2Osm para generar los
archivos. ¿Es posible que se trate de algún error del archivo
"zoning.geojson"? ¿Vale la pena repetir el proceso sin usar la versión de
desarrollo de CatAtom2Osm?

[1] https://drive.google.com/open?id=1HmvYfnKur0xt1cJQUJp8OCnA2Ry-30uq

**Comment by javiersanp** [comment]
Hola

En el archivo zoning.geojson que me has enviado, efectivamente falta la geometría de la zona rústica r023. La lista de coordenadas está vacía:

{ "type": "Feature", "properties": { "localId": "12029A021", "label": "r023", "levelName": "(1:POLIGONO )", "zipcode": "12029" }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },

Por eso el gestor de tareas no admite el archivo. He generado el municipio (12029) en mi ordenador y "a mi no me pasa" (típica escusa de programador). He usado la versión 1.2dev con QGIS 2.18.26. Tengo que hacer más pruebas a ver si consigo reproducir el problema.

**Comment by javiersanp** [comment]
Continuamos en
https://github.com/OSM-es/CatAtom2Osm/issues/40

Saludos
