### ISSUE TITLE
No se crea la carpeta tasks

### ISSUE THREAD

**Issue by JordiMFimport** [OSM-es/CatAtom2Osm#42]
Hola,

He intentado generar y corregir los archivos a importar en el proyecto de importación del Catastro de València, pero algo ha salido mal.
Tras corregir el nombre de algunas calles en el archivo "highway_names.csv", he vuelto a lanzar el comando "catatom2osm 46900" para generar y corregir los archivos a importar. Esta tarea ha tardado 4 días en completarse (el ordenador no se ha apagado nunca). Hoy, cuando ha terminado, he visto que catatom2Osm muestra algún error y no se han generado algunos archivos como "review.txt" ni la carpeta "tasks".
Adjunto el archivo "report" y una imagen de catatom2Osm.

[report.txt](https://github.com/OSM-es/CatAtom2Osm/files/3262953/report.txt)

![Captura3](https://user-images.githubusercontent.com/46328523/59057270-4e35ca80-889a-11e9-995c-fdd7efe581f4.JPG)

¿Creéis que tiene alguna solución?
Saludos,
Jordi

**Comment by javiersanp** [comment]
Reproducido en mi ordenador. Me pongo a depurarlo y te digo.

**Comment by javiersanp** [comment]
El fallo se produce por que al método ConsLayer.move_address le llegan geometrías no validas (WkbType() == WKBUnknown) en la capa buildings. Éstas no vienen de origen, sino que se generan en los métodos ConsLayer.merge_building_parts y PolygonLayer.simplify. Estos métodos tienen salvaguardias para que no se produzcan modificaciones de las geometrías en caso de que el resultado sea una geometría incorrecta, pero por algún motivo por determinar no son efectivas. Los identificadores de las características con geometría invalida producidas son:

# ConsLayer.merge_building_parts:
5227509YJ2752G_part5

# PolygonLayer.simplify
5109327YJ2751A_part1
5216712YJ2751E_part11
5448709YJ2754E_part14
5448709YJ2754E_part16
5448709YJ2754E_part25
5448709YJ2754E_part30
5477908YJ2757F_part1
5477940YJ2757E_part4
5677105YJ2757F_part1
5699408YJ2659H_part5
6140110YJ2764A_part2
9372902YJ2697C_part2

**Comment by JordiMFimport** [comment]
Muchas gracias Javier.

Entiendo que, como simple usuario de catatom2osm, no puedo hacer nada por ayudarte a identificar el problema. Si necesitas que realice alguna tarea de prueba, puedo hacerlo. Un saludo,
Jordi

**Comment by javiersanp** [comment]
Gracias por el ofrecimiento. Si tuvieras un ordenador más rápido si, pero
viendo tu registro, el mío tarda menos. Aún así son varias horas entre cada
prueba.

**Comment by javiersanp** [comment]
El error se produce por que al realizar las correcciones topológicas y de simplificación algunas modificaciones producen geometrías inválidas que no son detectadas por el método isGeosValid. Añado comprobación convirtiendo la geometría a multipolígono, además de la anterior. Si el multipolígono está vacío, la geometría no es correcta.
