### ISSUE TITLE
Error en MacOs 

### ISSUE THREAD

**Issue by JesusLopTem** [OSM-es/CatAtom2Osm#43]
Me sucede tanto en 10.14.5 como en 10.13.6 (Mojave e High Sierra). Realizo todo el proceso de instalación y va correcto hasta que intento descargar alguna zona, entonces me lanza estos dos errores: ERROR - No module named qgis.core
ERROR - Por favor instala QGIS
Qgis está instalado ( y reinstalado ) con los paquetes de KyngChaos, no veo donde puede estar el problema. Gracias.

**Comment by JordiMFimport** [comment]
Me sucede exactamente el mismo problema, pero estoy en Windows. En mi caso, creo que se debe a que no he instalado GQIS usando el instalador OSGeo4W en red. Si lo hago mediante ese método, el asistente me obliga a instalar la versión 3.X de QGIS. Como yo quería instalar la versión 2.18 de QGIS, no he usado ese asistente y, por tanto, creo que ahora me salta ese error. No sé si en MacOs puede tener algo que ver.

Saludos.

PD: El motivo por el que quiero instalar la versión QGIS 2.18 es porque si se instala la versión 3, luego te ves obligado a usar la versión 1.2 de desarrollo de Catatom2Osm. En cambio, yo quiero usar la versión 1.1.8.

**Comment by javiersanp** [comment]
Hola Jesús
Perdón por no haberte atendido. El problema se debe sin duda a que no localiza la instalación de QGIS. Tienes que revisar las variables definidas en el fichero pyqgis3mac.sh y comprobar que QGIS está instalado en QGISHOME. Te recomiendo usar el programa con Docker. https://hub.docker.com/r/egofer/catatom2osm

Jordi, prueba la última versión >= 1.2.2. Si quieres usar una versión anterior puedes hacerlo también con Docker. Sigue las instrucciones en el repositorio de Emilio y añade la etiqueta de la versión a cada referencia del mismo, por ejemplo:

docker pull egofer/catatom2osm:1.1.14
