### ISSUE TITLE
ERROR - No module named PyQt5.QtCore en Windows 10

### ISSUE THREAD

**Issue by JordiMFimport** [OSM-es/CatAtom2Osm#44]
Hola,

Estoy intentando usar la versión 1.1.8. de Catatom2Osm en Windows 10, pero no consigo hacerlo funcionar porque cuando lanzo el comando "catatom2osm 46900" (València) me sale el siguiente error:
"ERROR - No module named PyQt5.QtCore"

Para empezar he intentado usar catatom2osm instalando solemente QGIS 2.18, pero no lo reconoce. Instalo QGIS 2 mediante un archivo .exe [1] porque no es posible hacerlo mediante el instalador OSGeo4W en red (te obliga a elegir QGIS 3). Al instalar únicamente QGIS 2.18, cuando lanzo el comando "catatom2osm 46900", salta los siguientes errores:
"ERROR - No module named qgis.core
ERROR - Please, install QGIS"
Puede que ésto sea debido a que no sé añadir las librerías si no es con el instalador OSGeo4W en red.

Por tanto, mi duda es la siguiente: ¿cómo puedo resolver alguno de estos errores para poder usar la versión 1.1.8?

Muchas gracias.

[1] http://download.osgeo.org/qgis/win64/

**Comment by javiersanp** [comment]
Hola
Perdón por no atenderte antes. Es un problema de instalación de QGIS. Prueba de nuevo con la versión más reciente >=1.2.2 o usa docker https://hub.docker.com/r/egofer/catatom2osm
Con docker puedes descargarte imágenes de versiones anteriores usando la etiqueta como, por ejemplo
docker pull egofer/catatom2osm:1.1.14
