### ISSUE TITLE
Faltan geometrías en zoning.geojson

### ISSUE THREAD

**Issue by jlinfante** [OSM-es/CatAtom2Osm#46]
He procesado los ficheros de Badalona (08015) y aparte de generar una zona muy grande (ver https://tareas.openstreetmap.es/project/126#task/4) que contiene todo aquello que no está en otros polígonos/tareas, he detectado lo siguiente.

En el fichero zoning.geojson, el polígono correspondiente al fichero u00184.osm.gz (ver https://github.com/OSM-es/catastro-import/blob/master/08015/u00184.osm.gz), solamente contiene un edificio, mientras que el fichero OSM contiene varios. También lo he detectado con el fichero u00182.osm.gz.

Adjunto el fichero report.txt con el resultado del proceso.

[report.txt](https://github.com/OSM-es/CatAtom2Osm/files/3394007/report.txt)

[zoning.zip](https://github.com/OSM-es/CatAtom2Osm/files/3394003/zoning.zip)

**Comment by javiersanp** [comment]
Hola
Siento no haberte atendido antes. La zona grande que mencionas (task/4) es una zona de rústica con otras zonas urbanas inscritas y resulta en un multipolígono. Es una particularidad de este municipio, pero no afecta para nada al proyecto. Se puede trabajar sin problemas.

Lo que comentas del fichero zoning.geojson es por lo siguiente. Los edificios en los datos de Catastro son geometrías multiparte, todos los que tienen la misma referencia catastral se consideran como una única geometría que puede estar compuesta por varios edificios separados. En estos casos (182, 184) hay una discrepancia entre el tamaño de las manzana urbana y los edificios. Es como si hubiera habido una reclasificación de terreno. No me preocuparía, tampoco afecta al proyecto.
