### ISSUE TITLE
Problemas con la suma de las direcciones de entrada y salida

### ISSUE THREAD

**Issue by JorgeSanzS** [OSM-es/CatAtom2Osm#51]
Me han salido unos problemas que no conozco que nunca me habían salido con la suma de las direcciones de entrada y de salida. Como pone en la wiki aviso para ver que sucede.

El report es el siguiente:
Municipio: Castellanos de Moriscos
Nombre en Catastro: CASTELLANOS DE MORISCOS
Código: 37092
Fecha: 03/05/20
Opciones: 37092
Superficie: 13.8 km²
Población: 1638 hab. (2009)
Wikipedia: https://www.wikipedia.org/wiki/es:Castellanos de Moriscos
Wikidata: https://www.wikidata.org/wiki/Q1628745

=Información del sistema=
Versión de la aplicación: CatAtom2Osm 1.2dev
Plataforma: Linux 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64
Versión de QGIS: 3.4.13-Madeira
Versión de GDAL: 2.2.3
Número de CPUs: 2
Frecuencia de CPU: 0.0 Mhz
Tiempo de ejecución: 29.6 segundos
Memoria total: 980.00 MB
Memoria física usada: 186.98 MB
Memoria virtual usada: 1557.26 MB

=Direcciones=

==Datos de entrada==
Fecha de origen: 2019-10-26
Número de características: 1009
  Tipo entrada: 774
  Tipo parcela: 235
Códigos postales: 1
Nombres de viales: 74

==Procesado==
Direcciones eliminadas por nombre de vía: 51
Direcciones sin número de portal eliminadas: 1
Direcciones sin edificio asociado eliminadas: 218
Direcciones correspondientes a edificios múltiples eliminadas: 131
Direcciones tipo parcela no únicas para su edificio eliminadas: 53

==Combinación==
Direcciones OSM: 9
Direcciones rechazadas por existir en OSM: 7

==Datos de salida==
Direcciones: 547
  En nodos de entrada: 287
  En edificios: 258
  Tipo addr:street: 544
  Tipo addr:place: 3

=Edificios=

==Datos de entrada==
Fecha de origen: 2019-10-26
Número de características: 3258
  Edificios: 758
  Partes de edificios: 2461
  Piscinas: 39

==Procesado==
Partes fuera de contorno eliminadas: 75
Partes bajo rasante eliminadas: 71
Contornos de edificios creados: 2
Edificios con geometrías multiparte: 153
Edificios resultantes de dividir multipartes: 329
Partes fusionadas al contorno: 1255
Partes adyacentes fusionadas: 183
Geometrías no válidas eliminadas: 2
Vértices en punta eliminados: 3
Vértices próximos fusionados: 95
Puntos topológicos creados: 922
Vértices simplificados: 1348

==Combinación==
Edificios/piscinas en OSM: 163
  Con conflicto: 148

==Datos de salida==
Nodos: 9339
Vías: 1903
Relaciones: 42
Número de características: 1850
  Edificios: 936
  Partes de edificios: 875
  Piscinas: 39
Recuento de tipos de edificios: yes: 16, barn: 94, industrial: 158, residential: 636, public: 18, office: 6, retail: 5, ruins: 3
Plantas sobre rasante (nivel: nº de edificios): 1: 340, 3: 43, 2: 340, 4: 29, 5: 5, 7: 1
Plantas bajo rasante (nivel: nº de edificios): 1: 100, 2: 4
Archivos de tareas de rústica: 1
Archivos de tareas de urbana: 87

=Problemas=
Validación del informe: 2
  La suma de las direcciones de salida y las eliminadas debe ser igual a las direcciones de entrada
  La suma de las direcciones en entradas y edificios debe ser igual a las direcciones de salida

**Comment by javiersanp** [comment]
Hola Jorge

Envíame el archivo highway_names.csv al correo javiersanp at gmail dot com

Saludos

**Comment by javiersanp** [comment]
Hola Jorge.
He conseguido reproducir el problema usando QGis3. Ahora queda averiguar que es lo que está pasando y solucionarlo. Mientras tanto te recomiendo que cambies a QGis2 temporalmente. Lo más sencillo es que utilices el contenedor Docker https://hub.docker.com/r/egofer/catatom2osm.

**Comment by javiersanp** [comment]
Salida en QGis2
=============
Versión de la aplicación: CatAtom2Osm 1.2.2
Versión de QGIS: 2.18.17
==Datos de entrada==
Fecha de origen: 2019-10-26
Número de características: 1.009
  Tipo entrada: 774
  Tipo parcela: 235
Códigos postales: 1
Nombres de viales: 74
==Procesado==
Direcciones eliminadas por nombre de vía: 51
Direcciones sin número de portal eliminadas: 1
Direcciones sin edificio asociado eliminadas: 218
Direcciones correspondientes a edificios múltiples eliminadas: 131
Direcciones tipo parcela no únicas para su edificio eliminadas: 53
==Combinación==
Direcciones OSM: 9
Direcciones rechazadas por existir en OSM: 7
==Datos de salida==
Direcciones: 548
  En nodos de entrada: 290
  En edificios: 258
  Tipo addr:street: 545
  Tipo addr:place: 3
    548 + (51+1+218+131+53+7) = 548 + 461 = 1009
    290 + 258 = 548


Salida en QGis3
=============
=Información del sistema=
Versión de la aplicación: CatAtom2Osm 1.2.2
Versión de QGIS: 3.13.0-Master
==Datos de entrada==
Fecha de origen: 2019-10-26
Número de características: 1009
  Tipo entrada: 774
  Tipo parcela: 235
Códigos postales: 1
Nombres de viales: 74
==Procesado==
Direcciones eliminadas por nombre de vía: 51
Direcciones sin número de portal eliminadas: 1
Direcciones sin edificio asociado eliminadas: 218
Direcciones correspondientes a edificios múltiples eliminadas: 131
Direcciones tipo parcela no únicas para su edificio eliminadas: 53
==Combinación==
Direcciones OSM: 9
Direcciones rechazadas por existir en OSM: 7
==Datos de salida==
Direcciones: 547
  En nodos de entrada: 287
  En edificios: 258
  Tipo addr:street: 544
  Tipo addr:place: 3
=Problemas=
  La suma de las direcciones de salida y las eliminadas debe ser igual a las direcciones de entrada
    547 + (51+1+218+131+53+7) = 547 + 461 = 1008 <> 1009
  La suma de las direcciones en entradas y edificios debe ser igual a las direcciones de salida
    287 + 258 = 545 <> 547

**Comment by JorgeSanzS** [comment]
Tengo los 2 instalador. Lo acabo de hacer con QGis2 y cómo dices sin problemas.

Gracias por mirarlo.

**Comment by javiersanp** [comment]
Te recomiendo actualizar a última versión 1.2.2 master.
