### ISSUE TITLE
ERROR - No se pueden leer los metadatos de 'CDAU'

### ISSUE THREAD

**Issue by yopaseopor** [OSM-es/CatAtom2Osm#53]
Al probarlo en Docker y me comunican que también en máquina virtual al intentar hacer el catatom2osm 04057 por primera vez (Láujar de Andarax) da el siguiente error ERROR - No se pueden leer los metadatos de 'CDAU'
En mi caso Docker en Win10

**Comment by egofer** [comment]
Ha cambiado la URL de la página de información alfanumerica del CDAU:

http://www.callejerodeandalucia.es/portal/web/cdau/inf_alfa

La nueva es:

https://www.callejerodeandalucia.es/portal/informaci%C3%B3n-alfanum%C3%A9rica

He hecho un pull request con el cambio.

Por si es necesario, adjunto el log en modo debug:

[debug.log](https://github.com/OSM-es/CatAtom2Osm/files/5137411/debug.log)

**Comment by javiersanp** [comment]
Gracias
