### ISSUE TITLE
Utilización de los datos del "Xeoportal IDE" del Concello de Santiago

### ISSUE THREAD

**Issue by lucumon** [OSM-es/CatAtom2Osm#55]
Buenas,

He estado pensando que quizá sería interesante utilizar los datos del xeoportal de Santiago (del cual tenemos autorización) para complementar la importación del catastro. Se pueden descargar todos los datos (creo) desde el apartado de [descargas](http://xeoportal.santiagodecompostela.gal/xeoportalsantiago/#/Descargas/66ed5d12356449c1be67f4239152ed8c) en formato shp, dwg, dgn y gml. He pensado que para el emparejamiento de calles OSM-Catastro se podrían utilizar los nombres utilizados por esta plataforma también, que una forma de conseguirlos sería sacarlos de los shp de la red viaria.
Complementar las geometrías de los edificios con las de catastro ya sería algo bastante mas complicado, pero creo que lo mejor es que la persona encargada de importar (por ahora parece que yo solo) utilizase el wms del xeoportal junto pnoa y catastro para determinar que geometría se ajusta mejor.

Un salúdo!

**Comment by javiersanp** [comment]
Hola.
El programa da prioridad a los nombres de las calles presentes en OSM frente a los de Catastro. Dado que Santiago es una ciudad bien cartografiada en OSM, no tiene sentido que añadamos otra fuente más que finalmente va a ser ignorada. Sería más fácil repasar las pocas calles que no tengan nombre y asignárselos en OSM antes de importar.
