### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by Crashillo** [OSM-es/CatAtom2Osm#57]
Me he topado con el siguiente error, únicamente para el pueblo 45164 Sonseca (Toledo), tanto antes de la última actualización como ahora. No me ha ocurrido con ningún otro municipio.

```
catastro@d6f524ce2099:~$ catatom2osm -t 45164
2021-03-31 19:23:05,668 - INFO - Comienza el procesado de '45164'
2021-03-31 19:23:05,846 - INFO - Leídos 521 características en '45164/A.ES.SDGC.CP.45164.cadastralzoning.gml'
2021-03-31 19:23:08,427 - INFO - Municipio: 'Sonseca'                                                                                                                                                              
2021-03-31 19:23:42,242 - INFO - Generado '45164/boundary.poly'                                                                                                                                                    
2021-03-31 19:23:42,435 - INFO - Descargando '45164/A.ES.SDGC.BU.45164.zip'
2021-03-31 19:23:44,918 - INFO - Leídos 5549 características en '45164/A.ES.SDGC.BU.45164.building.gml'                                                                                                            
2021-03-31 19:23:56,480 - INFO - Leídos 14932 características en '45164/A.ES.SDGC.BU.45164.buildingpart.gml'                                                                                                       
2021-03-31 19:24:14,778 - INFO - Leídos 384 características en '45164/A.ES.SDGC.BU.45164.otherconstruction.gml'                                                                                                    
2021-03-31 19:50:53,481 - INFO - Descargando 'current_building.osm'                                                                                                                                                
2021-03-31 19:51:03,613 - INFO - Leído 'current_building.osm': 5107 nodos, 2078 vías, 3 relaciones
2021-03-31 19:51:09,599 - INFO - Generado 'current_building.osm': 5018 nodos, 2027 vías, 3 relaciones                                                                                                              
Traceback (most recent call last):
  File "/opt/CatAtom2Osm/main.py", line 113, in <module>
    run()
  File "/opt/CatAtom2Osm/main.py", line 105, in run
    process(options)
  File "/opt/CatAtom2Osm/main.py", line 39, in process
    app.run()
  File "/opt/CatAtom2Osm/catatom2osm.py", line 134, in run
    self.process_tasks(self.building)
  File "/opt/CatAtom2Osm/catatom2osm.py", line 199, in process_tasks
    self.get_tasks(source)
  File "/opt/CatAtom2Osm/catatom2osm.py", line 247, in get_tasks
    if last_task[0] == 'r':
IndexError: string index out of range
```

**Comment by javiersanp** [comment]
Hola. Cuando pasen las vacaciones lo miro.

**Comment by javiersanp** [comment]
Fallo localizado. En el archivo de zonificación de este municipio faltan zonas. El programa peta al intentar crear las tareas para los edificios que no pueden asignarse a ninguna zona.

**Comment by javiersanp** [comment]
El problema está corregido en la versión 1.3.4 del programa. Lo que hace es meter los edificios que no tienen zona en la tarea 'missing.osm.gz'. Es un poco chapuza por que esta tarea no aparece en el archivo de definición del proyecto zoning.geojson. Además falla la comprobación que asigna el 'fixme' de parte fuera del edificio y se asigna a todas las geometrías incorrectamente.
Quizá sería mejor esperar unos meses a la próxima revisión de Catastro a ver si corrigen el error.

**Comment by Crashillo** [comment]
Muchas gracias, actualizaré la imagen y probaré de nuevo; supongo que si me vuelvo a topar con esto, lo trataré como si fuese la tarea #0.
No confío demasiado en la revisión de catastro por _motu proprio_, ¿conoces dónde se les puede comunicar algo así de este carácter técnico?

**Comment by javiersanp** [comment]
+34 902 37 36
Paseo de la Castellana, 272
***@***.***

¿Te encargas tú?

**Comment by Crashillo** [comment]
Buenas @javiersanp, he visto que la imagen de Docker no se ha actualizado todavía y Emilio me ha comentado que es posible que los tests no hayan pasado en Travis para que se produzca el despliegue. ¿Puedes echarle un ojo? Thx

**Comment by javiersanp** [comment]
Hola. Los test en mi máquina salen correctos. @egofer mira en Travis a ver si dice algo en los logs. ¿Cual es la dirección?

**Comment by egofer** [comment]
Hola.
Veo que de los pull requests están fallando los [tests para el #52 y el #54](https://travis-ci.org/github/OSM-es/CatAtom2Osm/pull_requests). El #52 devuelve:

```bash
$ git fetch origin +refs/pull/52/merge:
fatal: couldn't find remote ref refs/pull/52/merge

The command "eval git fetch origin +refs/pull/52/merge: " failed. Retrying, 2 of 3.
fatal: couldn't find remote ref refs/pull/52/merge

The command "eval git fetch origin +refs/pull/52/merge: " failed. Retrying, 3 of 3.
fatal: couldn't find remote ref refs/pull/52/merge

The command "eval git fetch origin +refs/pull/52/merge: " failed 3 times.
The command "git fetch origin +refs/pull/52/merge:" failed and exited with 128 during .
Your build has been stopped.
```
Los PR están ambos cerrados, que puede ser por lo que no los encuentre.
Además #52 y #54 tiran ambos el siguiente error:

```bash
Skipping the install step, as specified in the configuration.

$ docker build -t $DOCKER_USERNAME/catatom2osm:test --build-arg REQUISITES=requisites-dev.txt .
invalid argument "/catatom2osm:test" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
The command "docker build -t $DOCKER_USERNAME/catatom2osm:test --build-arg REQUISITES=requisites-dev.txt ." exited with 125.

$ docker run --rm $DOCKER_USERNAME/catatom2osm:test /bin/bash -c "cd /opt/CatAtom2Osm && python -m unittest discover"
docker: invalid reference format.
See 'docker run --help'.
The command "docker run --rm $DOCKER_USERNAME/catatom2osm:test /bin/bash -c "cd /opt/CatAtom2Osm && python -m unittest discover"" exited with 125.

$ docker build -t $DOCKER_USERNAME/catatom2osm:latest .
invalid argument "/catatom2osm:latest" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
The command "docker build -t $DOCKER_USERNAME/catatom2osm:latest ." exited with 125.

Done. Your build exited with 1.
```

**Comment by Crashillo** [comment]
En los builds con éxito, existen dos pasos (previos a mostrar la versión de bash) que son `export DOCKER_USERNAME=` y `export DOCKER_PASSWORD=`. En los builds fallidos, estos no aparecen.

**Comment by javiersanp** [comment]
@egofer los PR que mencionas son de hace meses. ¿No te da opción a iniciar un build manualmente?

**Comment by javiersanp** [comment]
Algo estaría haciendo mal. He hecho un pequeño cambio al programa para generar una nueva versión, la 1.3.5 y esta si la ha detectado Travis. Al menos en master, la rama 1.3.5 ha fallado. Ya está actualizada la imagen en docker.

**Comment by egofer** [comment]
Vale, he vuelto a reiniciar un nuevo build de la 1.3.3 y ya aparece la 1.3.5.

![Screenshot_20210414_130819](https://user-images.githubusercontent.com/3096716/114701491-2c71be00-9d23-11eb-8eda-1d8d20812ab8.png)
 

La imagen ya está disponible en Docker Hub. He actualizado el contenedor local y ya es la versión 1.3.5.

**Comment by Crashillo** [comment]
@javiersanp el correo que me has indicado de Catastro aparece ofuscado por Github. ¿Puedes volver a enviarlo sin que quede oculto?

**Comment by javiersanp** [comment]
Si. Sacado de [aquí](http://www.idee.es/csw-inspire-idee/srv/spa/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&outputSchema=http://www.isotc211.org/2005/gmd&ElementSetName=full&ID=ES_SDGC_CP_ATOM).

    soporte.inspire@catastro.minhap.es

**Comment by Crashillo** [comment]
He recibido un correo automático de entrega fallida:
`Esta es la respuesta del servidor remoto:
550 5.7.1 Delivery not authorized, message refused(optenet)`

Parece ser que no quieren ser contactados de esta manera. :disappointed:

**Comment by egofer** [comment]
Prueba sino con la dirección contacto que aparece en la [solicitud GetCapabilities](https://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx?REQUEST=GetCapabilities&SERVICE=WMS[img][/img]) del servicio WMS de Catastro.

**Comment by Crashillo** [comment]
Nah, tampoco. Este de hecho tiene el dominio deshabilitado ya.

`DNS Error: 2520243 DNS type 'mx' lookup of catastro.meh.es responded with code NOERROR 2520243 DNS type 'mx' lookup of catastro.meh.es had no relevant answers. 2520243 DNS type 'aaaa' lookup of catastro.meh.es responded with code NOERROR 2520243 DNS type 'aaaa' lookup of catastro.meh.es had no relevant answers. 2520243 DNS type 'a' lookup of catastro.meh.es responded with code NOERROR 2520243 DNS type 'a' lookup of catastro.meh.es had no relevant answers.`

**Comment by javiersanp** [comment]
Habría que contactarles para decirles que actualicen los metadatos. LOL
