### ISSUE TITLE
Dividir municipios grandes

### ISSUE THREAD

**Issue by Crashillo** [OSM-es/CatAtom2Osm#58]
¿Es posible o se podría implementar una manera de dividir en pequeños cachos aquellos municipios más grandes?

Mismamente madrid. He intentado generar poco a poco: primero `catatom2osm -m 28900`, esto tarda un tiempo, pero es realizable. Ahora bien, al ejecutar `catatom2osm -t 28900`:

```sh
...
2021-10-02 02:20:20,719 - INFO - Leídos 124183 características en '28900/A.ES.SDGC.BU.28900.building.gml'                                                                                                          
2021-10-02 02:22:20,878 - INFO - Leídos 839881 características en '28900/A.ES.SDGC.BU.28900.buildingpart.gml'                                                                                                      
2021-10-02 02:26:59,179 - INFO - Leídos 14170 características en '28900/A.ES.SDGC.BU.28900.otherconstruction.gml'                                                                                                  
Topología:   0%|▍                                                                                                                                   | 2810/941469 [4:55:05<179:50:00,  1.45it/s, file=building.shp]
```

Los dos primeros `gml`, building y buildingpart, le toma unas horas, aceptable. Pero al llegar a otherconstruction olvídate, le he tenido toda la noche y apenas ha avanzado como puedes ver en el indicador de progreso.

Mi primera duda es, como dije al comienzo, si es posible dividir el municipio, mediante un boundary.poly o algo similar. Y la segunda es qué es ese othercontruction que le cuesta tantísimo procesar, ¿quizás pueda evitarse?

**Comment by javiersanp** [comment]
Es posible hacerlo, fácil y no hace falta modificar el programa. Está [documentado](https://wiki.openstreetmap.org/wiki/ES:Catastro_espa%C3%B1ol/Importaci%C3%B3n_de_edificios/Gu%C3%ADa_de_importaci%C3%B3n/Gesti%C3%B3n_de_proyectos#Anexo:_Modificar_proyectos).

**Comment by javiersanp** [comment]
Respecto al problema de tiempo de proceso la única solución es una máquina más potente.

**Comment by javiersanp** [comment]
Modificar el programa para que trabaje sobre trozos más pequeños que un municipio no es fácil. Se me ocurre que edites los archivos A.ES.SDGC.*.zip con QGIS, los fracciones y lances el el programa contra los trozos. ¿Me explico?

**Comment by javiersanp** [comment]
Añadirle una opción al programa para que no procese las piscinas (otherconstruction) es más fácil de programar. Puedo ponerme con ello. De todas formas, no tarda por las piscinas (14170 frente a 124183+839881). Tarda por que está revisando la topología de los edificios.

**Comment by javiersanp** [comment]
Centrándonos en la opción de procesar municipios grandes en trozos más pequeños, lo he estado pensando y tienes razón, sería posible modificar el programa para que trabajara sobre un trozo más pequeño. Es interesante y lo voy a estudiar.

**Comment by javiersanp** [comment]
La unidad de trabajo para la salida sería una zona. Las zonas pueden ser polígonos de rústica o parcelas de urbana. Las primeras se identifican internamente por el campo 'label' , un número de tres dígitos, las segundas por uno de cinco. Este número aparece a determinadas escalas como una etiqueta en el centro de la zona en los mapas de Catastro. Para facilitar su localización se puede incluir en zoning.geojson como paso previo de #65.

**Comment by javiersanp** [comment]
El parámetro CLI podría ser 
  -o [label], --z(o)ne [label]  Procesa edificios y direcciones de la zona identificada por 'label'. Combinar con -b si se desea sólo edificios o con -d si se desea sólo direcciones.

**Comment by javiersanp** [comment]
Aunque las etiquetas de manzanas urbanas tienen 5 dígitos, su valor entero puede coincidir con una etiqueta de polígono rústico. Por ejemplo 00010 y 010. Habrá que separar dos opciones para rústica y urbana.

    -r [label], --rustic [label]
    -u [label], --urban [label]

**Comment by javiersanp** [comment]
El filtrado espacial por los límites de la zona no funciona. Los límites son muy imprecisos y pasan por encima de los edificios. 

La otra opción es filtrar por la referencia catastral que incluye la etiqueta de la zona. De esta forma pueden aparecer algún edificio cercano a la zona pero son pocos casos y al menos cada edificio queda unívocamente dentro de una zona.

Para una referencia urbana, la etiqueta de la manzana ocupa los 5 primeros caracteres.
    label = '60860'
    localid = '6086003CS7458N'
    regexp_match('localId', '^' + label)

Para una referencia rústica la etiqueta del polígono ocupa la posición 7 a 9. 
    label = '005'
    localid = '38900A00500304'
    regexp_match('localId', '^.{6}' + label)

**Comment by Crashillo** [comment]
Pregunto desde la ignorancia, cuando se generan las tareas, cada una tiene sus límites en los que están bien contenidos los edificios (no cortados). Por tanto, ¿se podría calcular si el bounding_box de una tarea está contenido en el polígono solicitado? De esa manera te asegurarías que los edificios no se cortan, ya que su tarea (su boundary) está contenido en el polígono solicitado. Me explico con una imagen:

![imagen](https://user-images.githubusercontent.com/817526/143213969-9741b949-068a-49b0-b2fd-f1a3fc63f8eb.png)

Las tareas verdes están dentro de la zona a exportar, así que sabes que sus edificios también. La blanca la descartarías, y la roja quedaría duda: se podría ignorar para la zona actual y generar otro grupo de tareas "limítrofes"; o bien calcular el área y ver si tiene más de un 50% de área dentro de la zona a crear.

¿Es posible enfocarlo de ese modo?

**Comment by javiersanp** [comment]
Si. Así lo estaba haciendo hasta ahora, pero salen demasiadas manzanas
("tareas") rojas. Es complicación innecesaria. Con la otra forma,
consultando por referencia, no pasa eso y es más rápido.

La idea en cualquier caso es que si dos edificios tiene paredes compartidas
acaben en la misma tarea. Si están en distintas tareas se duplicarán nodos
al subir, pero si se pasa el validador de Josm avisa.

Eso va a ocurrir al trabajar por zonas más que si se toma todo el
municipio. Lo único es tenerlo en cuenta.

**Comment by javiersanp** [comment]
La estrategia de consulta por referencia catastral no funciona. Los resultados de las pruebas muestran que hay edificios cuya referencia no se ajusta al esquema comentado más arriba y se quedan sin asignar a ninguna zona. Hay que regresar a la consulta espacial con la siguiente estrategia.
* Para evitar las zonas rojas incluir los edificios que están contenidos y los que se superponen a la zona.
* Para evitar que un edificio salga en dos zonas distintas llevar un registro en un archivo de los edificios que ya tienen asignada una zona.

**Comment by Crashillo** [comment]
¿Sería posible comprobar si el tamaño (veáse área, o incluso valdría con el punto central) de cada tarea/edificio entra en la "zona a crear"? Por ejemplo, en el dibujo la zona roja, está ligeramente más fuera que dentro, por lo que quedaría fuera de la zona que estamos creando; no se generaría.

**Comment by javiersanp** [comment]
Realizadas pruebas para construir un índice de referencia_catastral:etiqueta_de_zona para todo el municipio de Madrid. Tiempo necesario aproximadamente 100 segundos con CPU de 4 núcleos a 3600 MHz. En la siguiente ejecución lo lee de archivo y no tarda nada. Da tiempo para asignar la zona cuando haya varias candidatas en función de la que tenga más área intersectada como sugiere @Crashillo.

En relación con #65, usar este índice para las tareas.

**Comment by javiersanp** [comment]
Pruebas

```
              05015            03001           38012
          1.3.10 1.5.0dev  1.3.10 1.5.0dev  1.3.10 1.5.0dev
nodos       2480  2478       8686  8688      19610 19637
vías         612   612       1668  1668       4516  4516
relaciones     0     0         10    10         53    53
edificios     518  518        883   883       2785  2785
partes        156  156        632   632       1923  1923
piscinas        0    0        157   157         26    26
direcciones   287  287        276   280        901   953

```

**Comment by javiersanp** [comment]
Recuento de tres municipios procesados al completo con la versión master y zona por zona con la versión de desarrollo. Coincide el número de edificios y partes. Las direcciones se incrementan por que la combinación con los datos de OSM se hace en un área más pequeña.

**Comment by javiersanp** [comment]
@Crashillo prueba la última versión disponible en [Docker](https://hub.docker.com/r/egofer/catatom2osm). Ya está operativo. Por ejemplo:

    catatom2osm -o 47798 28900

En la opción -o le pones la etiqueta de la zona que quieres procesar. Es el número de color violeta que sale en el centro de las manzanas y polígonos en el mapa de Catastro. En las ejecuciones posteriores del municipio va un poco más rápido. 

De esta forma puedes sacar un listado de todas las zonas disponibles.

    catatom2osm --list-zones 28900
