### ISSUE TITLE
Integración continua

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#61]
Ha dejado de operar https://travis-ci.org/ el proveedor de integración continua que usábamos para pasar las imágenes al hub de Docker.

Hay que buscar una alternativa.

**Comment by Crashillo** [comment]
Por sencillez, al estar aquí alojado, usaría Github Actions

**Comment by javiersanp** [comment]
Puede ser. Por ahora estoy usando la orden publish configurada en el
Makefile. Lo que echo de menos son los test que realizaba y almacenaba
Travis.
