### ISSUE TITLE
Zonificación de CAtastro

### ISSUE THREAD

**Issue by paunofu** [OSM-es/CatAtom2Osm#70]
En Alcalalí (03006) en el fichero de zonificación de Catastro falta la zona 02.

**Comment by javiersanp** [comment]
Creo que es el primer municipio que veo que le pasa esto. Los edificios 'perdidos' deberían haber terminado en una tarea. Lo he corregido.

Elimina el archivo 03006/cons_labels.csv, vuelve a ejecutar y comprueba que se ha creado 03006/tasks/missing.osm.gz

Puedes seguir adelante, pero en el archivo de definición del proyecto 'zoning.geojson' falta la geometría de '002'. Lo he modificado a mano, utiliza el que está en el repositorio catastro-import.
