### ISSUE TITLE
Rendimiento de la opción --zones

### ISSUE THREAD

**Issue by Crashillo** [OSM-es/CatAtom2Osm#73]
He estado cavando un poco más en el código y veo lo siguiente:

https://github.com/OSM-es/CatAtom2Osm/blob/89394161b07c5dd7cd2843bce8f911b93796b33a/catatom2osm/__main__.py#L36-L45

Aquí confirmo que se está llamando constantemente al programa en función del número de zonas (como pregunté por telegram), por lo que hará multitud de pasos, que a mi entender, son innecesarios.

He encontrado esto. Según supongo el `source.getFeatures()` devolverá un array, que es el que se puede filtrar en función del `label` que se haya introducido, en vez de hacer el `for` sobre todos los elementos.
https://github.com/OSM-es/CatAtom2Osm/blob/89394161b07c5dd7cd2843bce8f911b93796b33a/catatom2osm/app.py#L296-L297

La idea es que el programa reduzca la cantidad de items q hay en los bucles, cuando hace el `process_tasks` o el `get_tasks`, ya que es redundante repetirlo. En vez de hacer el bucle en el `create_and_run` (solo debería ejecutarse una vez) hacerlo sobre la cantidad de tasks (features) que hay.

**Comment by javiersanp** [comment]
Te paso este enlace por que te estoy viendo apuntar maneras
https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/vector.html#iterating-over-vector-layer

Te cuento la historia de la opción. En un principio había dos formas principales de ejecutar el programa. Con la opción -b se genera un único archivo. Con la opción -t, después de procesar los edificios los reparte en tareas. Cuando apareció la opción -o aceptaba un único parámetro de zona y seguí la primera línea solo que al final llama al resultado <label>.osm.gz en lugar de building.osm.gz. Luego diste la idea de aceptar varias zonas en -o y simplemente lo metí en un bucle. Tienes razón en que será más eficiente procesar todas las zonas de un tirón, pero creo que se conseguirá mucho. En las pruebas que he hecho, el procesado de la zonificación es sólo el 1% del total. De todas formas miro a ver si no es complicado procesar al estilo -t.

**Comment by Crashillo** [comment]
Si es que lo que me raya del asunto, es que procesar menos features tarde un rango similar de tiempo. Es decir, que un municipio con X features (x. ej. Oviedo, 3 horas) si le pasas un barrio con la décima parte del tamaño total, acabe tardando quizá no 3, pero un par de horas. Tendría que tardar, pues la décima parte, 18min.

Suponiendo que el `source.getFeatures()` es un array o similar, yo sugeria algo así:

```python
zonas = [11000, 11001...]
features = source.getFeatures()
featuresFiltered = filter(lambda feature: feature in zonas, scores)
for i, feat in enumerate(featuresFiltered): 
```

no sé la sintaxis de python, lo he encontrado por ahi, tal vez se tenga que usar `numpy`. Intentaré cacharrear en un fork. Pero la idea es esa, que menos features, por lógica, es menos tiempo.

**Comment by javiersanp** [comment]
@Crashillo mira los últimos commits. Todavía faltan varias cosas,  revisar y corregir errores. 

Usar output_buildings no era buena idea. Es la opción -b que esta pensada para temas de depuración. El archivo buildings.osm es  Demasiado grande, tiene una marca que impide  hacer la subida Le faltan los comentarios. La tareas estaban saliendo mal. Ahora se generan en process_tasks.

Antes se generaba un highway_names.csv para cada tarea, con distinto nombre para no sobrescribirlos.  No tiene sentido por qué se repetirán los nombres de muchas calle y es más trabajo vuelvo a ponerlo en un único archivo. El usuario tiene que ocuparse de  renombrarlo si procesa distintos barrios para no perderlo. 

Antes no se estaba generando el fichero address.osm que es importante para los nombres de las calles tardarán poco más en procesar.

Tampoco se estaba haciendo el proceso en dos fases que es necesario para que el usuario revisé los nombres de las calles.

Hay que echar a pelear las 2 versiones quitándole las cosas adicionales que se han añadido para comparar el tiempo de ejecución.

Falta generar un fichero de zonificación del barrio que se está procesando para facilitar al usuario que no tenga que editar el zoning a mano.

También podemos pasar un fichero geojson con el area a procesar cómo querías tu el principio para no tener que usar herramientas externas.

**Comment by javiersanp** [comment]
Prueba

     catatom2osm 28900 -o 30015 30088 99545

Versión de la aplicación: CatAtom2Osm 1.8.6
Tiempo de ejecución: 834,0 segundos

Versión de la aplicación: CatAtom2Osm 1.9.0.dev.0
Tiempo de ejecución: 364,4 segundos

**Comment by javiersanp** [comment]
Prueba

    catatom2osm 05015 -o $(catatom2osm --log=ERROR --list-zones 05015)

Versión de la aplicación: CatAtom2Osm 1.8.6
Tiempo de ejecución: 944,6 segundos

Versión de la aplicación: CatAtom2Osm 1.9.0.dev.0
Tiempo de ejecución: 49,5 segundos

¡Ey! ¡20 veces más rápido!

Quizá lo más importante es que las llamadas a Overpass que descargan los tres archivos current*.osm se realizan una única vez para todo el conjunto en lugar de por zonas.

**Comment by Crashillo** [comment]
Joder esta última ejecución es tremendamente notable. Cierto es que las llamadas externas, al no ser controlable su tiempo de ejecución, es necesario minimizarlas.

**Comment by javiersanp** [comment]
El problema si le pides un barrio o distrito muy grande es que Overpass te soltará un timeout en toda la boca.
En ese caso hay que descargar un PBF con los datos OSM y filtrarlo con un poly, como se explica [aquí](https://wiki.openstreetmap.org/wiki/ES:Catastro_espa%C3%B1ol/Importaci%C3%B3n_de_edificios/Conversi%C3%B3n_de_datos/Programa#Descarga_manual_de_datos_para_combinaci.C3.B3n), llamando a bin/extract.sh

**Comment by Crashillo** [comment]
Estaba mirando [esto](https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/vector.html#iterating-over-a-subset-of-features) pero he probado con la version de _development_ y parece que `self.building` ya se queda reducido cuando hay zonas, es por esto `query=self.zone_query` ??

**Comment by Crashillo** [comment]
Respecto a las queries de overpass, lo que se me ocurre es no hacerlas separadas sino todas a la vez, y una vez se tiene la respuesta, filtrar las features en base a las mismas props que se usaron para definir las queries.

Asimismo se podría establecer un timeout dinámico en función del area que se quiera descargar

**Comment by javiersanp** [comment]
> Estaba mirando [esto](https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/vector.html#iterating-over-a-subset-of-features) pero he probado con la version de _development_ y parece que `self.building` ya se queda reducido cuando hay zonas, es por esto `self.building.append(building_gml, query=self.zone_query)` ??

Si. query es un filtro, que append pasa a cada feature. Si devuelve true la copia, si false no.

Al principio de desarrollar el programa, probé distintas opciones para ver cual era la más rápida. Usar capas de datos en memoria (proveedor "memory"), shapefiles, creo recordar que incluso base de datos. Distintas formas de hacer consultas, con índices espaciales, por identificador, con filtros, secuencial. El código está en test/benchmanrk.py Ya no corre, pero en los comentarios tiene las conclusiones que saqué en su momento.

Al final, lo más rápido en promedio era usar shapefiles (con los gml no se puede hacer mucho), leer el gml secuencialmente completo y pasar al shp las features que interesen.

**Comment by javiersanp** [comment]
> Respecto a las queries de overpass, lo que se me ocurre es no hacerlas separadas sino todas a la vez, y una vez se tiene la respuesta, filtrar las features en base a las mismas props que se usaron para definir las queries.

Es decir, ¿en lugar de las tres consultas actuales (current_address.osm, current_building.osm y current_highway.osm) pedirlo todo en una única consulta? 

> Asimismo se podría establecer un timeout dinámico en función del area que se quiera descargar

Buenas sugerencias las dos. No se me habían ocurrido.

**Comment by javiersanp** [comment]
¿Te animas a meterle mano?

**Comment by javiersanp** [comment]
> Al principio de desarrollar el programa, probé distintas opciones para ver cual era la más rápida. Usar capas de datos en memoria (proveedor "memory"), shapefiles, creo recordar que incluso base de datos. Distintas formas de hacer consultas, con índices espaciales, por identificador, con filtros, secuencial. El código está en test/benchmanrk.py Ya no corre, pero en los comentarios tiene las conclusiones que saqué en su momento.

Más sobre el tema en https://github.com/OSM-es/CatAtom2Osm/wiki/Test-velocidad

**Comment by Crashillo** [comment]
> Es decir, ¿en lugar de las tres consultas actuales (current_address.osm, current_building.osm y current_highway.osm) pedirlo todo en una única consulta?

Exacto, puesto que en overpass cada linea actúa como un OR, la idea es juntarlo en una sola:

```
...
way["highway"]["name"];
way["place"="square"]["name"];
way["addr:street"]["addr:housenumber"];
way["addr:place"]["addr:housenumber"];
way[building];
way[leisure=swimming_pool];
...
``` 
Y luego por python hacer la clasificación
```python
current = self.read_osm('current.osm', ql=ql)
current_highway = set()
current_addr = set()
...
for d in current.elements:
   if 'highway' or 'place' in d.tags:
      current_highway.add(...)
   if 'addr:street' or 'addr:place' in d.tags:
      current_addr.add(...)
...

```
> ¿Te animas a meterle mano?

Ayer ya me puse a mirar los valores retornados de la consulta, una clase OSM

**Comment by javiersanp** [comment]
Si, osm.OSM. Necesitaríamos sacar los elementos y meterlos en otras instancias de OSM para generar los archivos current_*.osm

Se puede añadir a OSM un método append(data, query) similar al que tiene layer.BaseLayer.

Estoy preparando unas muestras y unas pruebas y ya te cuento.

**Comment by Crashillo** [comment]
Estaba justo haciendo estre método en `layer.py`

```python
    def remove_outside_features(self, geometry):
        """Remove from self any feature not contained in geometry features."""
        for feat in self.getFeatures():
            geom = feat.geometry()
            if not geometry.contains(geom):
                self.deleteFeature(feat.id())
```

Lo he pensado de esta manera puesto que no veía tan eficiente pasarle el layer como parámetro, y recorrer las features para generar el geometry total. De este modo, en `app.py` creas el split_geom que quieras una sola vez y es lo que le pasas a esta función.
Ahora bien, habría que modificar los tests para crear la `split_geom` **antes** de que se llame a `remove_outside_features`

**Comment by javiersanp** [comment]
He añadido el método append a osm.Osm.

El código en app habría que cambiarlo así:

Método nuevo. Llamarlo en la línea 113

    def get_current_osm(self):
        """Returns osm data for conflation"""
        ql_highway = [
            'way["highway"]["name"]',
            'relation["highway"]["name"]',
            'way["place"="square"]["name"]',
            'relation["place"="square"]["name"]',
        ]
        ql_addr = [
            'node["addr:street"]["addr:housenumber"]',
            'way["addr:street"]["addr:housenumber"]',
            'relation["addr:street"]["addr:housenumber"]',
            'node["addr:place"]["addr:housenumber"]',
            'way["addr:place"]["addr:housenumber"]',
            'relation["addr:place"]["addr:housenumber"]',
        ]
        ql_building = [
           'way[building];relation[building];'
           'way[leisure=swimming_pool];relation[leisure=swimming_pool]'
        ]
        ql = ql_highway + ql_addr + ql_building
        current_osm = self.read_osm('current_data.osm', ql=ql)
        return current_osm

Modificaciones

    def get_current_ad_osm(self, current_osm):
        """Gets OSM address for address conflation"""
        query = lambda el: (
            'addr:street' in el.tags or 'addr:place' in el.tags
        )
        address_osm = osm.Osm()
        address_osm.append(current_osm, query)

        ...
        return current_address

    def get_current_bu_osm(self, current_osm):
        """Gets OSM buildings for building conflation"""
        query = lambda el: (
            'building' in el.tags or el.tags.get('leisure') == 'swimming_pool'
        )
        current_bu_osm = osm.Osm()
        current_bu_osm.append(current_osm, query)
        return current_bu_osm

    def get_highway(self):
        """Gets OSM highways needed for street names conflation"""
        query = lambda el: (
            'highway' in el.tags or el.tags.get('place') == 'square'
        )
        highway_osm = osm.Osm()
        highway_osm.append(current_osm, query)
        ...
        return highway


    def process_building(self):
        ...
        if not self.options.manual:
            current_bu_osm = self.get_current_bu_osm()
            self.building.conflate(current_bu_osm):
            self.write_osm(current_bu_osm, 'current_building.osm')
            del current_bu_osm

    def delete_current_osm_files(self):
        if log.getEffectiveLevel() != logging.DEBUG:
            fn = self.get_path('current_data.osm')
            if os.path.exists(fn):
                os.remove(fn)

**Comment by Crashillo** [comment]
Bien, la idea era justo así, modificando el proceso, solo una duda: ¿siempre es necesario pedir addrs, buildings, highways? Por si en algunas opciones no fuese necesario traer tanto datos, q estén bajo condicionales

**Comment by javiersanp** [comment]
Esa era la ventaja de pedirlo por separado, pero yo no me preocuparía. En las opciones que se usan normalmente es necesario pedirlos todos. 

Se podría poner condicionales en `get_current_osm` para construir la consulta, pero es un lío por que la siguiente vez que se ejecuta coge los datos del fichero que se crea la primera vez y no hace la consulta. El programa podría esperar que estén unos datos y resulta que no están dependiendo de las opciones introducidas. Mejor cogerlo todo.

**Comment by javiersanp** [comment]
Pruebas con las opciones por defecto del programa (-tbd), ejecución en dos fases

tbd v1.8.6 run1
results/prod/tbd/03001/report.txt:Tiempo de ejecución: 16,0 segundos
results/prod/tbd/03006/report.txt:Tiempo de ejecución: 22,9 segundos
results/prod/tbd/05015/report.txt:Tiempo de ejecución: 9,1 segundos
results/prod/tbd/17072/report.txt:Tiempo de ejecución: 36,8 segundos
results/prod/tbd/38004/report.txt:Tiempo de ejecución: 56,0 segundos
results/prod/tbd/38012/report.txt:Tiempo de ejecución: 77,9 segundos

tbd v1.8.6 run2
results/prod/tbd/03001/report.txt:Tiempo de ejecución: 38,5 segundos
results/prod/tbd/03006/report.txt:Tiempo de ejecución: 98,1 segundos
results/prod/tbd/05015/report.txt:Tiempo de ejecución: 14,0 segundos
results/prod/tbd/17072/report.txt:Tiempo de ejecución: 1.295,1 segundos
results/prod/tbd/38004/report.txt:Tiempo de ejecución: 1.543,0 segundos
results/prod/tbd/38012/report.txt:Tiempo de ejecución: 1.645,3 segundos

tbd v1.9.0.dev.10 run1
results/dev/tbd/03001/report.txt:Tiempo de ejecución: 11,3 segundos
results/dev/tbd/03006/report.txt:Tiempo de ejecución: 18,6 segundos
results/dev/tbd/05015/report.txt:Tiempo de ejecución: 5,4 segundos
results/dev/tbd/17072/report.txt:Tiempo de ejecución: 32,1 segundos
results/dev/tbd/38004/report.txt:Tiempo de ejecución: 42,5 segundos
results/dev/tbd/38012/report.txt:Tiempo de ejecución: 49,4 segundos

tbd v1.9.0.dev.10 run2
results/dev/tbd/03001/report.txt:Tiempo de ejecución: 59,2 segundos
results/dev/tbd/03006/report.txt:Tiempo de ejecución: 177,0 segundos
results/dev/tbd/05015/report.txt:Tiempo de ejecución: 21,3 segundos
results/dev/tbd/17072/report.txt:Tiempo de ejecución: 1.949,1 segundos
results/dev/tbd/38004/report.txt:Tiempo de ejecución: 2.340,5 segundos
results/dev/tbd/38012/report.txt:Tiempo de ejecución: 2.512,9 segundos

@Crashillo  Tenemos que echar una pensadita a ver por que tarda más que antes.

**Comment by Crashillo** [comment]
La primera pasada siempre es más rápida, la segunda es la que se enrosca en algo. Mi primera duda, ¿por qué hay dos pasadas? ¿qué se supone que hace cada cual?

Por otro lado dices que ambas ejecuciones son con los parámetros por defecto, vamos que no hay zonas ni nada entiendo. ¿Qué diferencias hay en el hilo de ejecución de la 1.8 vs la 1.9? Es decir, la traza, por cuales funciones pasa. Al tardar más en las segundas ejecuciones, presupongo que es porque pasa por mayor número de sitios; si en la versión 1.9 tarda más, será porque pasa por más sitios.

Habrá que poner marcas temporales para calcular el tiempo que les lleva a las funciones

**Comment by javiersanp** [comment]
La primera es una pasada rápida dirigida a generar el archivo highway_names.csv. Un humano tiene que revisar este fichero siguiendo los pasos de la wiki, editarlo y poner los nombres correctos de las calles. Entonces se ejecuta la segunda pasada y usa ese fichero para los nombres de las calles. Por supuesto tarda mucho más por que procesa los edificios, mientras que en la otra no.

Si hay que mirar los log y la salida de ambas versiones y comparar.

**Comment by javiersanp** [comment]
El rendimiento de la opción -o ha mejorado mucho, pero no es normal que tarde *menos* que con -tbd

o v1.9.0.dev.10 run1
results/dev/o/03001/report.txt:Tiempo de ejecución: 7,0 segundos
results/dev/o/03006/report.txt:Tiempo de ejecución: 9,5 segundos
results/dev/o/05015/report.txt:Tiempo de ejecución: 5,0 segundos
results/dev/o/17072/report.txt:Tiempo de ejecución: 30,7 segundos
results/dev/o/38004/report.txt:Tiempo de ejecución: 18,3 segundos
results/dev/o/38012/report.txt:Tiempo de ejecución: 13,6 segundos

o v1.9.0.dev.10 run2
results/dev/o/03001/report.txt:Tiempo de ejecución: 31,4 segundos
results/dev/o/03006/report.txt:Tiempo de ejecución: da error
results/dev/o/05015/report.txt:Tiempo de ejecución: 14,9 segundos
results/dev/o/17072/report.txt:Tiempo de ejecución: 1.719,5 segundos
results/dev/o/38004/report.txt:Tiempo de ejecución: 396,8 segundos
results/dev/o/38012/report.txt:Tiempo de ejecución: 167,9 segundos

Si se consiguen tiempos tan buenos podemos pasar a procesar el municipio completo como si se hiciera con la opción -o, pero antes hay que comprender bien todo y comprobar que los resultados son los mismos. 

03006 da un error que hay que depurar. Otra cosa rara es que 38004 y 38012 con -o tardan bastante menos que 17072, mientras que con -tbd tardan más.

Esta es una comparación de la opción -tbd con v1.8.6 y -o con v1.9.0.dev.10

$ bin/comp.sh prod/tbd dev/o 03001

    exp          prod/tbd/03001  dev/o/03001  diff
    nodos        8686            8684         -2
    vías         1668            1668         0
    relaciones   10              10           0
    edificios    881             881          0
    partes       634             634          0
    piscinas     157             157          0
    direcciones  276             276          0

$ bin/comp.sh prod/tbd dev/o 05015

    exp          prod/tbd/05015  dev/o/05015  diff
    nodos        2480            2480         0
    vías         612             612          0
    relaciones   0               0            0
    edificios    517             517          0
    partes       157             157          0
    piscinas     0               0            0
    direcciones  287             287          0

$ bin/comp.sh prod/tbd dev/o 17072

    exp          prod/tbd/17072  dev/o/17072  diff
    nodos        61553           61516        -37
    vías         16649           16649        0
    relaciones   609             609          0
    edificios    6581            6581         0
    partes       9692            9692         0
    piscinas     264             264          0
    direcciones  3741            3739         -2

$ bin/comp.sh prod/tbd dev/o 38004

    exp          prod/tbd/38004  dev/o/38004  diff
    nodos        37917           37920        3
    vías         7809            7809         0
    relaciones   182             182          0
    edificios    4246            4246         0
    partes       3482            3482         0
    piscinas     143             143          0
    direcciones  736             732          -4

$ bin/comp.sh prod/tbd dev/o 38012

    exp          prod/tbd/38012  dev/o/38012  diff
    nodos        19607           19600        -7
    vías         4516            4516         0
    relaciones   53              53           0
    edificios    2782            2782         0
    partes       1926            1926         0
    piscinas     26              26           0
    direcciones  896             881          -15

**Comment by javiersanp** [comment]
La explicación está en una disminución del tiempo que se tarda en simplificar nodos.

    catatom2osm 38012 (v1.8.6)
    15:33:32,42            Usando Python 2.7.17
    15:33:45,81     0,0    Creados 2 puntos topológicos en la capa 'rusticzoning'
    15:34:46,01    60,2    Simplificados 3782 vértices en la capa 'rusticzoning'
    15:34:47,31     0,0    Fusionados 2 vértices en punta en la capa 'urbanzoning'
    15:35:21,56    34,3    Simplificados 7633 vértices en la capa 'urbanzoning'
    15:35:55,87     0,0    Fusionadas 252 partes adyacentes
    15:38:36,98   161,1    Simplificados 5780 vértices en la capa 'building'
    15:39:14,24     0,1    ¡Terminado!
                 341,82

    Simplificar  255,57

    catatom2osm 38012 (v1.9.0.dev.10)
    15:33:33,28            Usando Python 2.7.17
    15:33:41,59     0,0    Creados 2 puntos topológicos en la capa 'rusticzoning'
    15:33:59,47    17,9    Simplificados 3800 vértices en la capa 'rusticzoning'
    15:34:00,76     0,0    Fusionados 2 vértices en punta en la capa 'urbanzoning'
    15:34:04,53     3,8    Simplificados 7639 vértices en la capa 'urbanzoning'
    15:34:48,92     0,0    Fusionadas 252 partes adyacentes
    15:35:37,77    48,9    Simplificados 5779 vértices en la capa 'building'
    15:36:18,90     0,1    ¡Terminado!
                 165,62

    Simplificar  70,51

    Diferencia en tiempo de proceso: 176,20 seg
    Diferencia en simplificar: 185,06 seg

**Comment by Crashillo** [comment]
He estado probando con pueblos pequeños los rendimientos sobre 1.9.0 y 1.8.6. Siempre ejecutando el programa con `-tbd`, he obtenido mejores tiempos en 1.9.0, aunque no hay una diferencia notable.

Sin embargo, cuando sí la había, me he fijado que suele ser cuando se hacen las consultas overpass, que se queda el terminal a veces como esperando. Así que es posible que cuando se hagan pruebas reiteradas el programa tarde porque está esperando respuesta, ya sea por un timeout, no haya slots u otra causa externa. Se me ocurre que ese punto se podría mockear:

```python
def get_response(url, stream=False):
    """Try many times to get a http response or raise exception"""
    for i in range(number_of_retries):
        response = requests.get(url, stream=stream, timeout=default_timeout)
        if response.status_code == requests.codes.ok:
            return response
    response.raise_for_status()
```
Es decir, sustituir temporalmente (para las pruebas) la llamada real `requests.get(url, stream=stream, timeout=default_timeout)` por otra falsa que devuelva directamente el fichero que se obtendría en caso de ir bien. De este modo, descartamos ese retraso no controlable.

Por cierto, tienes buena máquina, que probando con tus selecciones, me suele llevar el doble de tiempo :D

**Comment by Crashillo** [comment]
Mirando más a fondo, para no interferir con otros métodos, sería identificar las que van contra overpass: aquellas cuyo `filename` acaba en `.osm`. Así que en el método `wget` se podría devolver el resultado de la consulta en `if filename.contains(".osm")`

**Comment by javiersanp** [comment]
Una forma de hacer que la prueba no dependa de terceros es ejecutar dos
veces. En la primera descarga los zip y los osm. Una vez que están
descargados lee de los archivos,  no se Internet

**Comment by javiersanp** [comment]
Algunas pruebas que hice tenían los datos de tiempo mal. Parece que al poner varios municipios en una única llamada al programa está sumando los datos que aparecen en el informe. Hay que corregirlo y reinicializar el informe.

**Comment by javiersanp** [comment]
Ahora ya me cuadran más los resultados al comparar con -o. Estos son los de -td

v1.8.6
javier@tierra:~/osm-es/CatAtom2Osm/results/prod/td$ grep Tiempo ?????/report.txt
03001/report.txt:Tiempo de ejecución: 19,8 segundos
03006/report.txt:Tiempo de ejecución: 55,7 segundos
05015/report.txt:Tiempo de ejecución: 13,4 segundos
17072/report.txt:Tiempo de ejecución: 1.120,0 segundos
38004/report.txt:Tiempo de ejecución: 206,3 segundos
38012/report.txt:Tiempo de ejecución: 93,3 segundos

v1.9.0.dev.11
javier@tierra:~/osm-es/CatAtom2Osm/results/dev/td$ grep Tiempo ?????/report.txt
03001/report.txt:Tiempo de ejecución: 32,6 segundos
03006/report.txt:Tiempo de ejecución: 101,3 segundos
05015/report.txt:Tiempo de ejecución: 15,3 segundos
17072/report.txt:Tiempo de ejecución: 1.552,7 segundos
38004/report.txt:Tiempo de ejecución: 334,4 segundos
38012/report.txt:Tiempo de ejecución: 149,4 segundos

**Comment by javiersanp** [comment]
El retardo que se produce para simplificar nodos podría deberse a este commit 395fe47

**Comment by javiersanp** [comment]
Confirmado

report-395fe47.txt:Tiempo de ejecución: 137,0 segundos
report-508c7f5.txt:Tiempo de ejecución: 77,9 segundos

**Comment by Crashillo** [comment]
¿Cómo puede ser que tardes más en `1.9.0` que en `1.8.6`? A mi no me pasaba, ¿ejecutas `-tbd` para ambas? Yo no probé todavía con `-o` y todas las zonas

**Comment by javiersanp** [comment]
Es al revés, tarda más.

Lo de -tbd es error mío. En realidad la opción equivalente a no usar
opciones es -td.

**Comment by javiersanp** [comment]
Una vez que descartemos python2 en la versión 2.0.0 podemos deshacer este cambio y se debería recuperar el rendimiento.

**Comment by javiersanp** [comment]
He juntado las tres consultas overpass en una sola y da "out of memory" incluso en municipios medianos.

**Comment by Crashillo** [comment]
Se puede usar el parámetro [maxsize](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Element_limit_.28maxsize:.29), de manera dinámica también en función del área solicitada. Aunque me resulta curioso que ocurra, no es una query "compleja" en términos de memoria.

**Comment by javiersanp** [comment]
Lo intenté, pero el servidor me puso en lista negra enseguida.

**Comment by Crashillo** [comment]
Prueba con otros servidores overpass, el oficial es el que tiene mayores restricciones. https://overpass.kumi.systems/api/ y https://overpass.openstreetmap.fr/api/ creo que son más... amables :D
¿de qué tamaños de municipios estaríamos hablando?

**Comment by javiersanp** [comment]
Empecé con mediados como 17072 38900, luego bajé a más pequeños como 38012
y nada.

**Comment by Crashillo** [comment]
Aunque te lo he comentado por telegram, lo dejo aquí para que quede constancia: ejecutando la query con madrid (se supone la más pesada/costosa) no existen problemas de restricciones y se ejecuta dentro de un tiempo más que razonable:
```
real  2m47,103s
user  0m4,340s
sys  0m6,689s
```

Ahora bien, de cara al desarrollo, probar con municipios enormes de manera sucesiva produce estos efectos, por lo que habría que descargarse 1 vez el fichero y mantenerlo en alguna carpeta temporal para evitar esos baneos del servidor

**Comment by javiersanp** [comment]
Descarto hacer todas las consultas a Overpass juntas por que con frecuencia devuelve runtime error: Query run out of memory using about 2048 MB of RAM. La ganancia de tiempo de respuesta cuando funciona (unos segundos) no merece el retraso cuando no funciona (y el inconveniente).
