### ISSUE TITLE
Formateo del código

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#77]
Reformatear el código y aplicar herramientas de comprobación y corrección automática.

flake8, black, isort, pydocstyle

Fichero de configuración tox.ini
```
[isort]
skip_glob = venv,.venv,.eggs,.tox

[pydocstyle]
add-ignore = D100,D101,D102,D103,D104,D105,D106,D107
```

Cambios a Makefile
```
BLACK_EXCLUDE_LIST := "(\.venv|\.git|bin)"

.PHONY: check
check:   ## Show the changes that the code formatters would apply.
	black -l 79 --diff --exclude $(BLACK_EXCLUDE_LIST) .
	isort --diff

.PHONY: format
format:   ## Run code formatters and apply it's changes.
	black -l 79 --exclude $(BLACK_EXCLUDE_LIST) .
	isort -y

.PHONY: style
style:   ## Check code styling.
	flake8
	pydocstyle
	isort --check-only -rc .


.PHONY: help
help:  ## Show this help.
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'
```

Estudiar poner un pre commit hook en git

**Comment by javiersanp** [comment]
# http://editorconfig.org
Archivo .editorconfig

```
root = true

[*]
indent_style = space
indent_size = 4
trim_trailing_whitespace = true
insert_final_newline = true
charset = utf-8
end_of_line = lf

[*.bat]
indent_style = tab
end_of_line = crlf

[LICENSE]
insert_final_newline = false

[Makefile]
indent_style = tab

[*.{diff,patch}]
trim_trailing_whitespace = false
```

**Comment by Crashillo** [comment]
> Estudiar poner un pre commit hook en git

En frontend se suele añadir https://github.com/typicode/husky o https://github.com/okonet/lint-staged. Te puede orientar para el hook

**Comment by Crashillo** [comment]
Este linter suele aparecer en las recomendaciones: https://www.pylint.org/

**Comment by javiersanp** [comment]
Lo miraré. https://pre-commit.com/ parece equivalente sin depender de npm

**Comment by Crashillo** [comment]
He estado mirando este tema, y parece que _black_ no es compatible con la versión 2 de python, a pesar de "supuestamente" tener un `black[python2]`. Es de los más famosos.

Otra alternativa a un hook de git, es incluir los linters encomo uno  un test independiente que colo compruebe el estilo y sintaxis

**Comment by javiersanp** [comment]
Podemos mirar alternativas a black o hacerlo como propones. Más o menos
relacionado con esto es sustituir unittest por pytest en las pruebas. Es
más moderno y permite más cosas.

**Comment by javiersanp** [comment]
No te había leído bien. Si la incompatibilidad es hacia atrás, no pasa
nada. En la 2.0.0 quitamos python 2.
