### ISSUE TITLE
Fichero de configuración

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#90]
Al meter el programa en docker ya no se puede tocar el archivo de configuración. Habilitar leer uno en la carpeta local.

**Comment by agarciamontoro** [comment]
No entiendo bien el objetivo de esta issue. Si ejecuto `make run` y después edito el archivo `catatom2osm/config.py`, veo los cambios en la consola.

Por ejemplo, he probado a cambiar el valor de `app_version` en el fichero a lo siguiente:
```python
app_version = "prueba"
```
y al ejecutar `catatom2osm -v` desde la consola iniciada con `make run`, el valor que se imprime es el nuevo:
```
catastro@a2676f0dacaa:~$ catatom2osm -v
prueba
```

Es probable que no esté entendiendo algo bien.

**Comment by javiersanp** [comment]
Hola. Si es que no está muy bien explicado. El fichero de configuración tiene una mezcla de parámetros que no se deben tocar y otros que el usuario puede modificar. No es el mejor método. Con el código metido dentro de la imagen docker no es sencillo para un usuario acceder a este fichero. Se vé que tu si lo has hecho, habrás accedido al interior del contenedor, pero el flujo normal es crear un contenedor para cada ejecución de forma transparente para el usuario usando los scripts lanzadores del programa.

La idea sería que config.py se quede como un módulo interno que no se toca y que exista la posibilidad de modificar algunos de sus parámetros si el usuario crea un fichero de configuración en la carpeta donde esté ejecutando el programa. El fichero podría ser config.json, por ejemplo.

Los parámetros que se puede modificar (exclusivamente) serían:

* language
* highway_types
* place_types
* remove_place_from_name
* excluded_types
* warning_min_area
* warning_max_area 

El código para leer el fichero de configuración podría ser un método get_user_config dentro del propio módulo config.py.
En __main__.py, lo primero que se haría sería llamar a este método. Si existe un archivo de configuración en el directorio actual, se lee la configuración del usuario. Si contiene alguno de los parámetros anteriores, reemplazar el contenido de la variable correspondiente.

Un ejemplo de un archivo de configuración:

```
{
    "language": "cat_ES.UTF-8",
    "remove_place_from_name": ["lloc", "conjunt", "diputació"],
    "warning_max_area": 50000,
}
```

Es muy fácil de leer con [json.loads](https://docs.python.org/3/library/json.html).

**Comment by javiersanp** [comment]
Me parece bien. Adelante.

**Comment by javiersanp** [comment]
v2.9.0
